# Generated by Django 3.2.9 on 2021-12-06 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=16)),
                ('membership', models.CharField(choices=[('R', 'Regular'), ('P', 'Premium'), ('N', 'Not a member')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('DC', 'Debit Card'), ('CC', 'Credit Card'), ('Ca', 'Cash')], max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('grocery_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.groceryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.purchase')),
            ],
        ),
    ]
